### ISSUE TITLE
Unhandled Exception error

### ISSUE THREAD

**Issue by PhantomMist** [TekkaGB/AemulusModManager#43]
So i am trying to use a music mod for persona 4 golden on pc through the mod manager and every time i build, I get an error saying a .raw file is being denied. I tried everything from exception from my antivirus software to full control of the files in the advance security.
![Screenshot (11)](https://user-images.githubusercontent.com/106404019/170791319-d401d8f0-b514-4e01-9dd0-c66663a9acef.png)

**Comment by TekkaGB** [comment]
Not sure what's going on if running as admin and disabling antivirus doesn't prevent this error. My only other guess is that your files are in cloud storage such as OneDrive.

**Comment by edgar1016** [comment]
I'm having the same issue tried moving folder to different drives, running as admin, I don't have an anti virus but I tried adding the folder as an exception to windows defender as well as disabling windows defender entirely. I don't have any cloud backups enabled on my PC. I have all dependencies installed as well. Happens when trying to unpack Persona 3 FES as well as when I try building.

OS: Windows 11 Build 22000.739

![AemulusPackageManager_loY2OibD2g](https://user-images.githubusercontent.com/13511581/177919735-ce3eda9f-4c32-4c88-8974-89470020ae7f.png)

**Comment by edgar1016** [comment]
Figured out the issue I was using a bad iso file. I thought it was weird that when using 7zip to look in the ISO file it only showed the AUDIO_TS and VIDEO_TS folders. I got a new ISO and it works now.
